version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build hello.go -o app.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.sh


# version: 0.1
            
# phases:

#   install: 
#     commands:
#       - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
#       - echo GOPATH - $GOPATH
#       - echo GOROOT - $GOROOT
#       - go get -u github.com/golang/lint/golint

#   pre_build: 
#     commands:

#       # Ensure code passes all lint tests
#       - golint -set_exit_status

#       # Run all tests included with our application
#       #- go test

#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Getting packages
#       - go get -u github.com/DeanThompson/ginpprof
#       - go get -u github.com/gin-contrib/cors
#       - go get -u github.com/gin-gonic/contrib/gzip
#       - go get -u github.com/gin-gonic/gin
#       - echo Compiling the Go code...
#       - go build -o app.sh
#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   files:
#     - app.sh
#     - app.go
#     - Dockerfile
